<?xml version="1.0" encoding="utf-8"?>
<testsuites tests="16" failures="0" disabled="0" errors="10" time="16" name="">
	<testsuite name="addTest" tests="0" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="addTest" />
	</testsuite>
	<testsuite name="SetDtatTest" tests="0" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="SetDtatTest" />
	</testsuite>
	<testsuite name="SetGlobalTestTest" tests="0" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="SetGlobalTestTest" />
		<testcase name="case 2" status="run" time="" classname="SetGlobalTestTest" />
	</testsuite>
	<testsuite name="CallScriptTestTest" tests="2" failures="" disabled="" errors="2" time="">
		<testcase name="case 1" status="run" time="" classname="CallScriptTestTest" />
		<testcase name="case 2" status="run" time="" classname="CallScriptTestTest">
			<failure message="case 2: signal SIGSEGV: Invalid memory reference, stop." type="error">&lt;!case 2: signal SIGSEGV: Invalid memory reference, stop.&gt;</failure>
		</testcase>
		<testcase name="case 3" status="run" time="" classname="CallScriptTestTest">
			<failure message="case 3: signal SIGSEGV: Invalid memory reference, stop." type="error">&lt;!case 3: signal SIGSEGV: Invalid memory reference, stop.&gt;</failure>
		</testcase>
	</testsuite>
	<testsuite name="localIOTest" tests="1" failures="" disabled="" errors="1" time="">
		<testcase name="case 1" status="run" time="" classname="localIOTest">
			<failure message="case 1: 被测试代码产生不明错误导致测试中断" type="error">&lt;!case 1: 被测试代码产生不明错误导致测试中断&gt;</failure>
		</testcase>
	</testsuite>
	<testsuite name="CallScriptTest_2Test" tests="5" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="CallScriptTest_2Test" />
		<testcase name="case 2" status="run" time="" classname="CallScriptTest_2Test" />
		<testcase name="case 3" status="run" time="" classname="CallScriptTest_2Test" />
		<testcase name="case 4" status="run" time="" classname="CallScriptTest_2Test" />
	</testsuite>
	<testsuite name="FunctionPtrStruct_2Test" tests="0" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="FunctionPtrStruct_2Test" />
		<testcase name="case 2" status="run" time="" classname="FunctionPtrStruct_2Test" />
	</testsuite>
	<testsuite name="FunctionPtrTest_2Test" tests="0" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="FunctionPtrTest_2Test" />
	</testsuite>
	<testsuite name="GlobalTest_2Test" tests="0" failures="" disabled="" errors="0" time="" />
	<testsuite name="localIO_2Test" tests="0" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="localIO_2Test" />
	</testsuite>
	<testsuite name="MockTest_2Test" tests="3" failures="" disabled="" errors="3" time="">
		<testcase name="case 1" status="run" time="" classname="MockTest_2Test">
			<failure message="case 1: return expected 2 but 100" type="error">&lt;!case 1: return expected 2 but 100&gt;</failure>
		</testcase>
		<testcase name="case 2" status="run" time="" classname="MockTest_2Test">
			<failure message="case 2: return expected 2 but 100" type="error">&lt;!case 2: return expected 2 but 100&gt;</failure>
		</testcase>
		<testcase name="case 3" status="run" time="" classname="MockTest_2Test">
			<failure message="case 3: return expected 2 but 100" type="error">&lt;!case 3: return expected 2 but 100&gt;</failure>
		</testcase>
	</testsuite>
	<testsuite name="pow_2Test" tests="5" failures="" disabled="" errors="4" time="">
		<testcase name="case 1" status="run" time="" classname="pow_2Test" />
		<testcase name="case 2" status="run" time="" classname="pow_2Test">
			<failure message="case 2: return expected 2 but 1" type="error">&lt;!case 2: return expected 2 but 1&gt;</failure>
		</testcase>
		<testcase name="case 3" status="run" time="" classname="pow_2Test">
			<failure message="case 3: return expected 3 but 1" type="error">&lt;!case 3: return expected 3 but 1&gt;</failure>
		</testcase>
		<testcase name="case 4" status="run" time="" classname="pow_2Test">
			<failure message="case 4: return expected 4 but 1" type="error">&lt;!case 4: return expected 4 but 1&gt;</failure>
		</testcase>
		<testcase name="case 5" status="run" time="" classname="pow_2Test">
			<failure message="case 5: return expected 5 but 1" type="error">&lt;!case 5: return expected 5 but 1&gt;</failure>
		</testcase>
	</testsuite>
	<testsuite name="localIO_3Test" tests="0" failures="" disabled="" errors="0" time="">
		<testcase name="case 1" status="run" time="" classname="localIO_3Test" />
	</testsuite>
</testsuites>
